# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Мой личный блог об онлайн зароботке в казино
email: helper@monclercoats.org
description:  Я играл каждый день и с остервенением высасывал из местных персонажей мелкие доллары. Кто играл в «Метле», знает тамошний контингент и понимает, что сидение там особого удовольствие не доставляет, но я довольно стабильно делал по 300$ в день в течение месяца. Происходило это легко, конечно, игра довольно нервная, есть много переездов, но в целом очень доходная. Рассказываю о личном опыте, как играть в онлайн казино в плюс, как обыграть ребят в покере или блэкджек 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://monclercoats.org" # the base hostname & protocol for your site
github_username:  kolyanblog.github.io

# Build settings
markdown: kramdown

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"
  - "jekyll-minifier"

plugins: 
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
